- name: Restart kubernetes
  become: true
  service:
    name: "{{ item }}"
    state: "restarted"      
    daemon_reload: true
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
