apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  namespace: clt-0
spec:
  type: NodePort
  ports:
    - name: https
      targetPort: https
      port: 443
      nodePort: 30000
  selector:
    app.kubernetes.io/component: apiserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-apiserver
  namespace: clt-0
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: apiserver
  template:
    metadata:
      labels:
        app.kubernetes.io/component: apiserver
    spec:
      automountServiceAccountToken: false
      containers:
        - name: apiserver
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          image: registry.k8s.io/kube-apiserver:v1.29.2
          command:
            - kube-apiserver
            - --advertise-address=$(HOST_IP)
            - --allow-privileged=true
            - --authorization-mode=Node,RBAC
            - --bind-address=0.0.0.0
            - --client-ca-file=/etc/kubernetes/server-certs/ca.crt
            - --endpoint-reconciler-type=lease
            - --etcd-cafile=/etc/kubernetes/etcd-client-certs/ca.crt
            - --etcd-certfile=/etc/kubernetes/etcd-client-certs/tls.crt
            - --etcd-keyfile=/etc/kubernetes/etcd-client-certs/tls.key
            - --etcd-servers=https://etcd:2379
            - --event-ttl=2h
            - --kubelet-certificate-authority=/etc/kubernetes/kubelet-client-certs/ca.crt
            - --kubelet-client-certificate=/etc/kubernetes/kubelet-client-certs/tls.crt
            - --kubelet-client-key=/etc/kubernetes/kubelet-client-certs/tls.key
            - --kubelet-preferred-address-types=InternalIP
            - --runtime-config=api/all=true
            - --secure-port=31111
            - --service-account-key-file=/etc/kubernetes/service-account-keys/tls.crt
            - --service-account-signing-key-file=/etc/kubernetes/service-account-keys/tls.key
            - --service-account-issuer=https://kubernetes.clt-1.svc.cluster.local
            - --service-cluster-ip-range=10.32.0.0/17
            - --service-node-port-range=30000-32767
            - --tls-cert-file=/etc/kubernetes/server-certs/tls.crt
            - --tls-private-key-file=/etc/kubernetes/server-certs/tls.key
            - --v=2
          ports:
            - name: https
              containerPort: 31111
          livenessProbe:
            httpGet:
              scheme: HTTPS
              port: https
              path: /livez
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: https
              path: /readyz
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop: [ALL]
              add: [NET_BIND_SERVICE]
          volumeMounts:
            - name: etcd-client-certs
              mountPath: /etc/kubernetes/etcd-client-certs
            - name: kubelet-client-certs
              mountPath: /etc/kubernetes/kubelet-client-certs
            - name: server-certs
              mountPath: /etc/kubernetes/server-certs
            - name: service-account-keys
              mountPath: /etc/kubernetes/service-account-keys
      restartPolicy: Always
      volumes:
        - name: etcd-client-certs
          secret:
            secretName: kube-apiserver-etcd-client
        - name: kubelet-client-certs
          secret:
            secretName: kube-apiserver-kubelet-client
        - name: server-certs
          secret:
            secretName: kube-apiserver
        - name: service-account-keys
          secret:
            secretName: service-account-keys
