apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-controller-manager
  namespace: clt-0
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller-manager
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 12345
        runAsUser: 12345
        runAsGroup: 12345
      initContainers:
        - name: setup-kubeconfig
          image: bitnami/kubectl:latest
          env:
            - name: KUBECONFIG
              value: /var/run/kubernetes/config
          command:
            - bash
            - -c
            - |
                kubectl config set-credentials default \
                    --client-key=/etc/kubernetes/tls.key \
                    --client-certificate=/etc/kubernetes/tls.crt \
                    --embed-certs=true
                kubectl config set-cluster default \
                    --certificate-authority=/etc/kubernetes/ca.crt \
                    --server=https://kube-apiserver:443 \
                    --embed-certs=true
                kubectl config set-context default \
                    --user=default \
                    --cluster=default
                kubectl config use-context default
          volumeMounts:
            - name: client-certs
              mountPath: /etc/kubernetes
            - name: temp
              mountPath: /var/run/kubernetes
      containers:
        - name: controller-manager
          image: registry.k8s.io/kube-controller-manager:v1.29.2
          command:
            - kube-controller-manager
            - --allocate-node-cidrs=true
            - --bind-address=0.0.0.0
            - --cluster-cidr=10.32.128.0/17
            - --cluster-name=kubernetes
            - --cluster-signing-cert-file=/etc/kubernetes/kubernetes-ca/tls.crt
            - --cluster-signing-key-file=/etc/kubernetes/kubernetes-ca/tls.key
            - --kubeconfig=/etc/kubernetes/controller-manager.conf
            - --leader-elect=true 
            - --root-ca-file=/etc/kubernetes/kubernetes-ca/ca.crt
            - --secure-port=10257
            - --service-account-private-key-file=/etc/kubernetes/service-account-keys/tls.key
            - --service-cluster-ip-range=10.32.0.0/17
            - --use-service-account-credentials=true 
            - --v=2
          ports:
            - name: https
              containerPort: 10257
          livenessProbe:
            httpGet:
              scheme: HTTPS
              port: https
              path: /healthz
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: https
              path: /healthz
          volumeMounts:
            - name: kubernetes-ca
              mountPath: /etc/kubernetes/kubernetes-ca
            - name: service-account-keys
              mountPath: /etc/kubernetes/service-account-keys
            - name: temp
              mountPath: /etc/kubernetes/controller-manager.conf
              subPath: config
      restartPolicy: Always
      volumes:
        - name: kubernetes-ca
          secret:
            secretName: kubernetes-ca
        - name: service-account-keys
          secret:
            secretName: service-account-keys
        - name: client-certs
          secret:
            secretName: kube-controller-manager
        - name: temp
          emptyDir: {}
