apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-scheduler
  namespace: clt-0
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    clientConnection:
      kubeconfig: "/etc/kubernetes/scheduler.conf"
    leaderElection:
      leaderElect: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-scheduler
  namespace: clt-0
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/component: scheduler
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 12345
        runAsUser: 12345
        runAsGroup: 12345
      initContainers:
        - name: setup-kubeconfig
          image: bitnami/kubectl:latest
          env:
            - name: KUBECONFIG
              value: /var/lib/kubernetes/config
          command:
            - bash
            - -c
            - |
                kubectl config set-credentials default \
                    --client-key=/etc/kubernetes/tls.key \
                    --client-certificate=/etc/kubernetes/tls.crt \
                    --embed-certs=true
                kubectl config set-cluster default \
                    --certificate-authority=/etc/kubernetes/ca.crt \
                    --server=https://kube-apiserver:443 \
                    --embed-certs=true
                kubectl config set-context default \
                    --user=default \
                    --cluster=default
                kubectl config use-context default
          volumeMounts:
            - name: client-certs
              mountPath: /etc/kubernetes
            - name: temp
              mountPath: /var/lib/kubernetes
      containers:
        - name: scheduler
          image: registry.k8s.io/kube-scheduler:v1.29.2
          command:
            - kube-scheduler
            - --bind-address=0.0.0.0
            - --config=/etc/kubernetes/config.yaml
            - --secure-port=10259
            - --v=2
          ports:
            - name: https
              containerPort: 10259
          livenessProbe:
            httpGet:
              scheme: HTTPS
              port: https
              path: /healthz
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: https
              path: /healthz
          volumeMounts:
            - name: kubernetes-ca
              mountPath: /etc/kubernetes/kubernetes-ca
            - name: service-account-keys
              mountPath: /etc/kubernetes/service-account-keys
            - name: temp
              mountPath: /etc/kubernetes/scheduler.conf
              subPath: config
            - name: config
              mountPath: /etc/kubernetes/config.yaml
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - name: kubernetes-ca
          secret:
            secretName: kubernetes-ca
        - name: service-account-keys
          secret:
            secretName: service-account-keys
        - name: client-certs
          secret:
            secretName: kube-scheduler
        - name: temp
          emptyDir: {}
        - name: config
          configMap:
            name: kube-scheduler
