apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-scheduler
  namespace: clt-0
spec:
  commonName: system:kube-scheduler
  secretName: kube-scheduler
  duration: 8760h0m0s
  renewBefore: 120h0m0s
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - client auth
  issuerRef:
    name: kubernetes-ca
    kind: Issuer
    group: cert-manager.io
