---
- name: Prepare kubernetes config dir
  become: true
  file:
    state: "directory"
    path: "/etc/kubernetes"
    owner: "root"
    group: "root"
    recurse: true

- name: Download binaries
  become: true
  get_url:
    force: true
    url: "https://dl.k8s.io/v{{ kubernetes_version }}/bin/linux/amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0755"
  notify:
    - "Restart kubernetes"
  loop:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kubectl

- name: Copy over certificates
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "/etc/kubernetes/{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "root"
    group: "root"
  loop:
  - src: "{{ kubernetes_serving_ca_cert_file }}"
    dest: serving-ca-cert.pem
    mode: "0644"
  - src: "{{ kubernetes_client_ca_cert_file }}"
    dest: client-ca-cert.pem
    mode: "0644"
  - src: "{{ kubernetes_client_ca_key_file }}"
    dest: client-ca-key.pem
    mode: "0600"
  - src: "{{ kubernetes_etcd_ca_cert_file }}"
    dest: etcd-ca-cert.pem
    mode: "0644"
  - src: "{{ kubernetes_etcd_client_cert_file }}"
    dest: etcd-client-cert.pem
    mode: "0644"
  - src: "{{ kubernetes_etcd_client_key_file }}"
    dest: etcd-client-key.pem
    mode: "0600"
  - src: "{{ kubernetes_kubelet_ca_cert_file }}"
    dest: kubelet-ca-cert.pem
    mode: "0644"
  - src: "{{ kubernetes_kubelet_client_cert_file }}"
    dest: kubelet-client-cert.pem
    mode: "0644"
  - src: "{{ kubernetes_kubelet_client_key_file }}"
    dest: kubelet-client-key.pem
    mode: "0600"
  - src: "{{ kubernetes_service_account_cert_file }}"
    dest: service-account-cert.pem
    mode: "0644"
  - src: "{{ kubernetes_service_account_key_file }}"
    dest: service-account-key.pem
    mode: "0600"
  - src: "{{ kubernetes_serving_cert_file }}"
    dest: serving-cert.pem
    mode: "0644"
  - src: "{{ kubernetes_serving_key_file }}"
    dest: serving-key.pem
    mode: "0600"
  notify:
    - "Restart kubernetes"

- name: Copy over scheduler config
  become: true
  copy:
    src: "scheduler-config.yaml"
    dest: "/etc/kubernetes/scheduler-config.yaml"
    mode: "0644"
    owner: "root"
    group: "root"

- name: Copy over kubeconfigs
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "/etc/kubernetes/{{ item.dest }}"
    mode: "0600"
    owner: "root"
    group: "root"
  loop:
  - src: "{{ kubernetes_controller_manager_kubeconfig_file }}"
    dest: controller-manager.conf
  - src: "{{ kubernetes_scheduler_kubeconfig_file }}"
    dest: scheduler.conf
  - src: "{{ kubernetes_super_admin_kubeconfig_file }}"
    dest: super-admin.conf

- name: Template systemd units
  become: true
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: "0644"
    owner: "root"
    group: "root"
  loop:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
  notify:
    - "Restart etcd"

- name: Enable and start systemd units
  become: true
  service:
    name: "{{ item }}"
    state: "started"
    enabled: true
    daemon_reload: true
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
