apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-super-admin
  namespace: clt-0
spec:
  commonName: kubernetes-super-admin
  secretName: kubernetes-super-admin
  duration: 8760h0m0s
  renewBefore: 120h0m0s
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
      - system:masters
  usages:
    - client auth
  issuerRef:
    name: kubernetes-ca
    kind: Issuer
    group: cert-manager.io
